### ISSUE TITLE
getting a panic with latest code

### ISSUE THREAD

**Issue by jopietsch** [osrg/rustybgp#118] opened 2021-11-30 17:38 UTC
using bgperf with bgpdump to send traffic

```
 python3 bgperf.py bench -n5 -trustybgp -p800000 -gbgpdump2 -s --mrt-file=/home/jpietsch/bgperf/rib.20210801.0000
```
get this output 
```
Hello, RustyBGPd (32 cpus)!
thread '<unnamed>' panicked at 'inconsistent in drop', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.18/src/str
eam/futures_unordered/abort.rs:11:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'panicking twice to abort the program', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-uti
l-0.3.18/src/stream/futures_unordered/abort.rs:6:13
stack backtrace:
   0:     0x56275aa72b6c - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs
:90:5
   1:     0x56275aa72b6c - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56275aa72b6c - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56275aa72b6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56275aa9498c - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x56275aa6cad5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x56275aa746e0 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56275aa746e0 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56275aa746e0 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x56275aa74297 - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x56275aa74d94 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x56275a9d83b5 - std::panicking::begin_panic::{{closure}}::hf826dffca46d009a
  12:     0x56275a9d8384 - std::sys_common::backtrace::__rust_end_short_backtrace::h86a5312ea5900044
  13:     0x56275a3102bc - std::panicking::begin_panic::hc8f1edb280a2e8ff
  14:     0x56275a9d82c9 - <futures_util::stream::futures_unordered::abort::abort::DoublePanic as core::ops::drop::Drop>::drop::h0336f65bb09
6aed5
  15:     0x56275a9d8237 - core::ptr::drop_in_place<futures_util::stream::futures_unordered::abort::abort::DoublePanic>::hb07f9406a11a3a1e
  16:     0x56275a9d82ae - futures_util::stream::futures_unordered::abort::abort::h3261bb903d9ba561
  17:     0x56275a6a4cb2 - core::ptr::drop_in_place<futures_util::stream::futures_unordered::FuturesUnordered<futures_util::stream::stream::
next::Next<tokio_stream::wrappers::mpsc_unbounded::UnboundedReceiverStream<rustybgpd::event::ToPeerEvent>>>>::h73aeffd02d895279
  18:     0x56275a7873c7 - rustybgpd::event::Handler::run::{{closure}}::h4fdabcfa710f3e5a
  19:     0x56275a746a0b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hb7e0bb100bcd89eb
  20:     0x56275a8b6935 - tokio::runtime::task::harness::Harness<T,S>::poll::h6ff7a6c1bb31a4e6
  21:     0x56275a8638b1 - std::thread::local::LocalKey<T>::with::ha297eda2128a4fd6
  22:     0x56275a6d0604 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h635a09920156b075
  23:     0x56275a7e78b5 - tokio::runtime::Runtime::block_on::hf377527235153e53
  24:     0x56275a838025 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf0a8a3f3550fe502
  25:     0x56275a864523 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h33ccad866afb2795
  26:     0x56275aa77e93 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf2a5e508372e2387
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
  27:     0x56275aa77e93 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h46642f5b75478456
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
  28:     0x56275aa77e93 - std::sys::unix::thread::Thread::new::thread_start::h1fbdb50adbde1cab
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
  29:     0x7f57c2788ea7 - start_thread
  30:     0x7f57c256edef - clone
  31:                0x0 - <unknown>
thread panicked while panicking. aborting
```

I don't get the problem with only 1 tester

**Comment by fujita** [comment] 2021-11-30 22:41
Hmm, I successfully executed the above command. The log doesn't look like related with the change about filtered routes. I reverted dumping up Tokio version. Can you try again? If it still doesn't work, please try rust 1.54 too.

**Comment by jopietsch** [comment] 2021-12-01 06:44
I do not understand what I've done, I can't get rustybgp to work in bgperf any more. I've tried previous versions of rustybgp, and deleting all docker images and starting over and I keep getting the same error.

**Comment by fujita** [comment] 2021-12-01 08:30
Did you execute 'update' command with --no-cache option to build rustybgp image with the latest commit?

**Comment by fujita** [comment] 2021-12-02 14:43
I was able to reproduce the problem. working on it now.

**Comment by fujita** [comment] 2021-12-02 15:22
I pushed the fix. I newly created the rustybgp image bgperf update command and successfully run the IXP filter test with https://github.com/jopietsch/bgperf/pull/7

**Comment by jopietsch** [comment] 2021-12-02 16:58
great! thanks for debugging and fixing this. and thanks for the bgperf PR as well!

**Comment by fujita** [comment] 2021-12-08 14:47
Closed this since the latest code works again on your env. I need to figure out why it doesn't work with latest async-executor library though...

**Closed by fujita** 2021-12-08 14:47 UTC
